### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by guohaotian0320** [CVMI-Lab/SC-GS#49]
When I run the train code, I get the following error: Traceback (most recent call last):                                                           | 0/80000 [00:00<? , ?it/s]
File "train_gui.py", line 1886, in <module>
gui.train(args.iterations)
File "train_gui.py", line 1000, in train
self.train_node_rendering_step()
File "train_gui.py", line 1276, in train_node_rendering_step
render_pkg_re = render(viewpoint_cam, self.deform.deform.as_gaussians, self. pipe, self. background, d_xyz, d_rot,  d_scale, random_bg_color=random_bg_color, d_opacity=d_opacity, d_color=d_color, d_rot_as_res=self.deform.d_rot_as_res)
File "/data2/ght/SC-GS-master/gaussian_renderer/__init__.py", line 157, in render
cov3D_precomp=cov3D_precomp)
ValueError: not enough values to unpack (expected 4, got 2)

The diff_gaussian_rasterization I installed is in the link, but it seems that the return parameters of the rendering function do not match, do you know how to solve it? Look forward to your reply!

**Comment by yihua7** [comment]
Hi,
Could you check the output of your installed rasterizer (e.g the number of tensors and their shapes)? It seems inconsistent with ours.

**Comment by guohaotian0320** [comment]
> Hi,
> Could you check the output of your installed rasterizer (e.g the number of tensors and their shapes)? It seems inconsistent with ours.
I used the  rasterizer  from your project link, but it only returned two variables, not four,

**Comment by yihua7** [comment]
Hi,
You should recheck it since the lib I recommend is from: https://github.com/ashawkey/diff-gaussian-rasterization/tree/d986da0d4cf2dfeb43b9a379b6e9fa0a7f3f7eea.
As you can see in its readme file the output has four elements.
